name: ci_pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
       runs-on: ubuntu-latest  
       
       steps:
        - uses: actions/checkout@v1
          with:
            fetch-depth: 0


        - name: Set up Python 3.9
          uses: actions/setup-python@v1
          with:
            python-version: 3.9


        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


        - name: Format
          run: |
            black app.py


        - name: Lint
          run: |
            pylint --disable=R,C  app.py


        - name: Test
          run: |
            python -m pytest -vv test.py 